# Generated by Django 5.0 on 2023-12-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_created_topic_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='host',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated',
        ),
    ]
